GET http://0.0.0.0:3000/base

###
GET http://0.0.0.0:3000/base/?cidade=Tóquio

###
GET http://0.0.0.0:3000/base/6404b132c3f0f9632abd9648
###

POST http://0.0.0.0:3000/base
Content-Type: application/json

{
    "titulo": "Fábrica de SMILE",
    "nomeFachada": "Coliseu Corroída",
    "cidade": "Rio de Janeiro",
    "tecnologias": ["laboratório de nanotecnologia","estande de tiro", "jardim de ervas venenosas"]
}

###

PUT http://0.0.0.0:3000/base/6404b132c3f0f9632abd9648
Content-Type: application/json

{
    "titulo": "Fábrica de SMILE",
    "nomeFachada": "Coliseu Corrida",
    "cidade": "Tóquio",
    "tecnologias": ["laboratório de nanotecnologia","estande de tiro", "jardim de ervas venenosas"]
}

###
DELETE http://0.0.0.0:3000/base/6404930c68fa555d4cd693db